

export const rowData = [
    {
        sno: 1,
        groomerName: "John Doe",
        status: "Grooming",
        specialization: "Dog Grooming",
        address: "Main Branch",
        rating: "4.8",
        appointments: 5,
    },
    {
        sno: 2,
        groomerName: "Sarah Smith",
        status: "Available",
        specialization: "Cat & Small Pet Grooming",
        address: "Downtown Branch",
        rating: "4.6",
        appointments: 2,
    },
    {
        sno: 3,
        groomerName: "Mike Johnson",
        status: "Absent",
        specialization: "Exotic Pets & Birds",
        address: "Uptown Branch",
        rating: "4.9",
        appointments: 0,
    },
];


export const dummyTrainerList = [
  {
    _id: "trainer_001",
    profile_image: "https://randomuser.me/api/portraits/men/75.jpg",
    first_name: "John",
    last_name: "Doe",
    email: "john.doe@example.com",
    phone_number: "+1234567890",
    address: "123 Fitness St, Fit City",
    gender: "Male",
    age: 29,
    country: "USA",
    city: "New York",
    specialization: "Strength Training",
    experience: "EXPERIENCE",
    experienceYear: 5,
    certificates: "https://example.com/certificates/john_doe_certificate.pdf",
    idProof: "https://example.com/idproofs/john_doe_id.pdf",
  },
  {
    _id: "trainer_002",
    profile_image: "https://randomuser.me/api/portraits/women/65.jpg",
    first_name: "Emma",
    last_name: "Smith",
    email: "emma.smith@example.com",
    phone_number: "+1987654321",
    address: "456 Wellness Ave, Healthy Town",
    gender: "Female",
    age: 32,
    country: "Canada",
    city: "Toronto",
    specialization: "Zumba & Cardio",
    experience: "FRESHER",
    experienceYear: "",
    certificates: "",
    idProof: "",
  },
  {
    _id: "trainer_003",
    profile_image: "https://randomuser.me/api/portraits/men/45.jpg",
    first_name: "Carlos",
    last_name: "Mendez",
    email: "carlos.mendez@example.com",
    phone_number: "+447123456789",
    address: "789 Power St, Muscle City",
    gender: "Male",
    age: 35,
    country: "UK",
    city: "London",
    specialization: "Bodybuilding",
    experience: "EXPERIENCE",
    experienceYear: 8,
    certificates: "https://example.com/certificates/carlos_certificate.pdf",
    idProof: "https://example.com/idproofs/carlos_id.pdf",
  },
  {
    _id: "trainer_004",
    profile_image: "https://randomuser.me/api/portraits/women/21.jpg",
    first_name: "Sophia",
    last_name: "Lee",
    email: "sophia.lee@example.com",
    phone_number: "+61412345678",
    address: "101 Fit Blvd, Wellness City",
    gender: "Female",
    age: 27,
    country: "Australia",
    city: "Sydney",
    specialization: "Yoga & Pilates",
    experience: "EXPERIENCE",
    experienceYear: 3,
    certificates: "https://example.com/certificates/sophia_lee_cert.pdf",
    idProof: "https://example.com/idproofs/sophia_id.pdf",
  },
];
